export const THEME_ANIMATION = '../ui/themes/animations.css';
export const THEME_BREAKPOINTS = '../ui/themes/breakpoints.css';
export const THEME_COLORS = '../ui/themes/colors.css';
export const THEME_ELEVATIONS = '../ui/themes/elevations.css';
export const THEME_FONTS= '../ui/themes/fonts.css';
export const THEME_SHADOWS = '../ui/themes/shadows.css';
export const THEME_SIZES = '../ui/themes/sizes.css';
export const THEME_SPACES = '../ui/themes/spaces.css';
export const THEME_WEIGHTS = '../ui/themes/weights.css';
