export const THEME_ANIMATION = '../../themes/animations.css';
export const THEME_BREAKPOINTS = '../../themes/breakpoints.css';
export const THEME_COLORS = '../../themes/colors.css';
export const THEME_ELEVATIONS = '../../themes/elevations.css';
export const THEME_FONTS= '../../themes/fonts.css';
export const THEME_SHADOWS = '../../themes/shadows.css';
export const THEME_SIZES = '../../themes/sizes.css';
export const THEME_SPACES = '../../themes/spaces.css';
export const THEME_WEIGHTS = '../../themes/weights.css';
