export const THEME_ANIMATION = '../../packages/themes/animations.css';
export const THEME_BREAKPOINTS = '../../packages/themes/breakpoints.css';
export const THEME_COLORS = '../../packages/themes/colors.css';
export const THEME_ELEVATIONS = '../../packages/themes/elevations.css';
export const THEME_FONTS= '../../packages/themes/fonts.css';
export const THEME_SHADOWS = '../../packages/themes/shadows.css';
export const THEME_SIZES = '../../packages/themes/sizes.css';
export const THEME_SPACES = '../../packages/themes/spaces.css';
export const THEME_WEIGHTS = '../../packages/themes/weights.css';
